# Ingestion Job for Administrative Law
version: 1.0
job_id: ingest_admin_law_20240521
description: "Process and ingest source documents for the Administrative Law branch."

source:
  path: "/kb/legal/branches/administrative_law/"
  documents:
    - "proclamation_1183_2020_administrative_procedure.pdf"

pipeline:
  - step: 1
    name: "Convert PDF to Text"
    tool: "PyMuPDF" # Preferred for accuracy over pdfminer.six
    tool_version: "1.23.8"
    output: "normalized.txt"
    params:
      clean_hyphenation: true
  - step: 2
    name: "Structure and Map"
    schema: "/src/legal_branches/_kb_schema.json#LegalKnowledge"
    output: "structured.json"
    target_collection: "articles"
  - step: 3
    name: "Lint and Verify"
    script: "/data_ingestion/scripts/amharic_linter.py"
    rules:
      - "ensure_legal_terminology"
      - "check_numeral_consistency"
  - step: 4
    name: "Seed to Firestore"
    target_collection: "articles"
    source_file: "structured.json"

governance:
  lineage_fields:
    source_doc_id: "proclamation_1183_2020"
    extracted_at: "{{timestamp}}"
    tool_version: "1.23.8"
    reviewer: "AI_AGENT_GEMINI"
  quality_gate:
    require_lint_pass: true
